### ISSUE TITLE
Compatibility with GNAT Pro 18.1

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-runtime#5]
Currently, we are using source code of the original Ada runtime from GCC 6.3. This code is quite old (copyright notice from 2013) and at some points very different from the code of the current GNAT Pro 18.1. For example the implementation of the secondary stack differs. The current GNAT binder generates the symbols `__gnat_binder_ss_count`, `__gnat_default_ss_pool`, `__gnat_default_ss_size`, which are unknown in older implementations.

To solve this issue we could use a more recent version of GCC to be compatible. The Ada-related source code in GCC 7.3 (copyright notice from 2016) still does not contain the changes mentioned above. Any objections against using GCC 8.1? @senier @jklmnn

**Comment by jklmnn** [comment]
We should stay backwards compatible since Genode uses GCC 6.3 and we can't simply change Genodes compiler. We still should support newer compiler versions. What you could do is provide different implementations (or one generic if this is doable) and link them together via a single c file that provides and selects the required symbols dependent on the used compiler version. You could to this via preprocessor checks as done in the current [Ada runtime used in Genode](https://github.com/genodelabs/genode/blob/246bacd9dad1db0b9c6c88beef869336414036ef/repos/libports/src/lib/ada/runtimelib/s-secsta_c.cc#L12). Instead of a warning you would provide the correct implementation/symbol for each compiler version.
