### ISSUE TITLE
Define interface for generic runtime

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#6]
Create a specification (.ads file) what needs to be implemented to adapt the generic runtime to a particular system.

**Comment by jklmnn** [comment]
The current interface definition looks as follows. Since some Ada functions take Ada Strings but require to pass null-terminated character buffers to the platform a body is needed to do this conversion. The package should be named `Platform`.

| Symbol                       | C signature                                      | Ada signature                                                                                      |
|------------------------------|--------------------------------------------------|----------------------------------------------------------------------------------------------------|
| `log_debug`                  | `void log_debug(char *)`                         | `procedure Log_Debug(Msg : String)`                                                                |
| `log_warning`                | `void log_warning(char *)`                       | `procedure Log_Warning(Msg : String)`                                                              |
| `log_error`                  | `void log_error(char *)`                         | `procedure Log_Error(Msg : String)`                                                                |
| `__gnat_malloc`              | `void *__gnat_malloc(size_t)`                    | `function Malloc(Size : Natural) return System.Address`                                            |
| `__gnat_free`                | `void __gnat_free(void *)`                       | `procedure Free(Ptr : System.Address)`                                                             |
| `__gnat_unhandled_terminate` | `void __gnat_unhandled_terminate()`              | `procedure Unhandled_Terminate`                                                                    |
| `allocate_secondary_stack`   | `void *allocate_secondary_stack(void *, size_t)` | `function Allocate_Secondary_Stack(Thread : System.Address; Size : Natural) return System.Address` |
| `get_thread`                 | `void *get_thread()`                             | `function Get_Thread return System.Address`                                                        |
| `raise_ada_exception`        | `void raise_ada_exception(char *, char*)`        | `procedure Raise_Ada_Exception(Name : String; Msg : String)`                                       |

@senier with the implementation of `a-except` that is currently available in this repo and with this spec we would loose our ability to determine the exception type in C++ since all exceptions would be called by `raise_ada_exception`. Is this a problem? Using only this one exception simplifies the platform interface and a message still would be available. Also what do we do if we catch a certain exception (except that we know the type to print it) since we probably can't handle it anyway?

**Comment by jklmnn** [comment]
We added a [specification](https://github.com/Componolit/ada-runtime/wiki/Platform-interface) of the platform-runtime-interface.

**Comment by senier** [comment]
I feel a bit uneasy about throwing away the exception type. His about adding a parameter indicating the exception type (using an enum)?

**Comment by jklmnn** [comment]
An enum with a case statement in the implementation on the side of Genode would indeed keep the current functionality with the targeted API. @treiher how do you think about this?

**Comment by treiher** [comment]
I agree with you. Let's add the parameter:

`raise_ada_exception` | `void raise_ada_exception(exception_type, char *, char*)` | `procedure Raise_Ada_Exception(T : Exception_Type; Name : String; Msg : String)`
-- | -- | --
